"""initial_schema

Revision ID: 2c40e78acd0b
Revises: None
Create Date: 2026-05-09 07:59:08.835499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision: str = '2c40e78acd0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('proxy_path', sa.String(length=512), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_cache_original_url'), 'image_cache', ['original_url'], unique=True)
    op.create_table('source_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('crawl_interval', sa.Integer(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_configs_type'), 'source_configs', ['type'], unique=False)
    op.create_table('raw_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('guid', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content_raw', sa.Text(), nullable=True),
    sa.Column('content_normalized', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'guid', name='uq_raw_items_source_guid')
    )
    op.create_index(op.f('ix_raw_items_content_hash'), 'raw_items', ['content_hash'], unique=True)
    op.create_index(op.f('ix_raw_items_published_at'), 'raw_items', ['published_at'], unique=False)
    op.create_index(op.f('ix_raw_items_source_id'), 'raw_items', ['source_id'], unique=False)
    op.create_index(op.f('ix_raw_items_status'), 'raw_items', ['status'], unique=False)
    op.create_table('processed_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('raw_item_id', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('recommended_score', sa.Float(), nullable=True),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('llm_model_used', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=False),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_items_category'), 'processed_items', ['category'], unique=False)
    op.create_index(op.f('ix_processed_items_raw_item_id'), 'processed_items', ['raw_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_items_raw_item_id'), table_name='processed_items')
    op.drop_index(op.f('ix_processed_items_category'), table_name='processed_items')
    op.drop_table('processed_items')
    op.drop_index(op.f('ix_raw_items_status'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_source_id'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_published_at'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_content_hash'), table_name='raw_items')
    op.drop_table('raw_items')
    op.drop_index(op.f('ix_source_configs_type'), table_name='source_configs')
    op.drop_table('source_configs')
    op.drop_index(op.f('ix_image_cache_original_url'), table_name='image_cache')
    op.drop_table('image_cache')
    # ### end Alembic commands ###
